### ISSUE TITLE
try running jaeger with ES as a backend

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#1321]
Jaeger is not showing traces that are too big, meaning that it is not very helpful precisely in the cases where we need to inspect traces.

I suggest we try to set up ES as its backend to see if this will improve the situation.

Ideally we should have a more resilient setup for Jaeger, even if the retention rate is small (let's say 1-2 hours). Right now, even if a test just completes, when it has timed-out and generated more traces, it doesn't show up in Jaeger.

Obviously this is also a problem in Swarm, but I think we should be able to at least scale Jaeger a bit more.

I will go through the traces that are useless and remove them (such as `send.offered.hashes` trace).

cc @skylenet

**Comment by skylenet** [comment]
A PR has been added so that we can choose between the elasticsearch backend: https://github.com/ethersphere/helm-charts/pull/77/files 

Soon, I'll add here an example of the correct env vars and cli args that we could use so that we target elasticsearch as a backend.

**Comment by skylenet** [comment]
Adding the following to the jaeger values should do the trick:

```yaml
config:
  env:
    SPAN_STORAGE_TYPE: elasticsearch
  args:
    - "--es.index-prefix=test"
    - "--es.server-urls=http://elasticsearch-client.logging.svc.cluster.local:9200"
```
