### ISSUE TITLE
Connection reset by peer when swarm is the part of a docker-compose setup

### ISSUE THREAD

**Issue by seniorjoinu** [ethersphere/swarm#2128]
#### System information

Swarm version: `0.5.4`
OS & Version: Official docker image from ethersphere/swarm on ubuntu 18.04

#### Expected behaviour
Executing `curl -X POST -H "Content-Type: text/plain" --data "this is example" http://0.0.0.0:8501/bzz:/` returns a hash of the stored file

#### Actual behaviour
Executing `curl -X POST -H "Content-Type: text/plain" --data "this is example" http://0.0.0.0:8501/bzz:/` produces `curl: (56) Recv failure: Connection reset by peer`

#### Steps to reproduce the behaviour
1. Append swarm to a project docker-compose.yml file like this:
```
version: '3'
services:
  swarm:
    image: "ethersphere/swarm:latest"
    ports:
    - "0.0.0.0:8501:8500/tcp"
```
2. Start the container with the following command: 
`docker-compose run --service-ports swarm`
3. Create a password and unlock the account
4. Execute mentioned curl command

P.S. Executing `docker run -p 8501:8500/tcp -it ethersphere/swarm  --httpaddr=0.0.0.0` instead of docker-compose works as expected.
